version: '1.0'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      NODE_ENV: production

networks:
  app-network:
    driver: bridge
